name: apple_color_list_example
description: "Demonstrates how to use the apple_color_list plugin."
publish_to: 'none'

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  apple_color_list:
    path: ../

  # file system
  path: ^1.9.0
  path_provider: ^2.1.4
  file_picker: ^8.1.2
  file_selector: ^1.0.3
  universal_platform: ^1.1.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
