// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsAppleColorListApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsAppleColorListApi(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsAppleColorListApi(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashAppleColorListApi(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashAppleColorListApi(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashAppleColorListApi(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Generated class from Pigeon that represents data sent in messages.
struct AppleColorList: Hashable {
  var name: String
  var colors: [AppleColor]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AppleColorList? {
    let name = pigeonVar_list[0] as! String
    let colors = pigeonVar_list[1] as! [AppleColor]

    return AppleColorList(
      name: name,
      colors: colors
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      colors,
    ]
  }
  static func == (lhs: AppleColorList, rhs: AppleColorList) -> Bool {
    return deepEqualsAppleColorListApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashAppleColorListApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AppleColor: Hashable {
  var name: String
  var red: Double
  var green: Double
  var blue: Double
  var alpha: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AppleColor? {
    let name = pigeonVar_list[0] as! String
    let red = pigeonVar_list[1] as! Double
    let green = pigeonVar_list[2] as! Double
    let blue = pigeonVar_list[3] as! Double
    let alpha = pigeonVar_list[4] as! Double

    return AppleColor(
      name: name,
      red: red,
      green: green,
      blue: blue,
      alpha: alpha
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      red,
      green,
      blue,
      alpha,
    ]
  }
  static func == (lhs: AppleColor, rhs: AppleColor) -> Bool {
    return deepEqualsAppleColorListApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashAppleColorListApi(value: toList(), hasher: &hasher)
  }
}

private class AppleColorListApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return AppleColorList.fromList(self.readValue() as! [Any?])
    case 130:
      return AppleColor.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class AppleColorListApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? AppleColorList {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? AppleColor {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class AppleColorListApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return AppleColorListApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return AppleColorListApiPigeonCodecWriter(data: data)
  }
}

class AppleColorListApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = AppleColorListApiPigeonCodec(readerWriter: AppleColorListApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AppleColorListApi {
  func readColorList(from path: String) throws -> AppleColorList
  func writeColorList(_ colorList: AppleColorList, to path: String) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AppleColorListApiSetup {
  static var codec: FlutterStandardMessageCodec { AppleColorListApiPigeonCodec.shared }
  /// Sets up an instance of `AppleColorListApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AppleColorListApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let readColorListChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_color_list.AppleColorListApi.readColorList\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readColorListChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        do {
          let result = try api.readColorList(from: pathArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      readColorListChannel.setMessageHandler(nil)
    }
    let writeColorListChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_color_list.AppleColorListApi.writeColorList\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      writeColorListChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let colorListArg = args[0] as! AppleColorList
        let pathArg = args[1] as! String
        do {
          try api.writeColorList(colorListArg, to: pathArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      writeColorListChannel.setMessageHandler(nil)
    }
  }
}
